In [10]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
  
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [11]:
text = '해보지 않으면 해낼 수 없다'

In [12]:
result = text_to_word_sequence(text)
print("<원문\n>", text)
print("\n<토큰화>\n",result)

<원문
> 해보지 않으면 해낼 수 없다

<토큰화>
 ['해보지', '않으면', '해낼', '수', '없다']


In [13]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]

In [14]:
token = Tokenizer()
token.fit_on_texts(docs)

In [15]:
print("<단어 카운트>\n", token.word_counts)

<단어 카운트>
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [16]:
print("<문장 카운트>\n", token.document_count)

<문장 카운트>
 3


In [17]:
print("<각 단어가 몇개의 문장에 포함되어 있는가>\n", token.word_docs)

<각 단어가 몇개의 문장에 포함되어 있는가>
 defaultdict(<class 'int'>, {'단어를': 1, '텍스트의': 2, '나누어': 1, '각': 1, '먼저': 1, '토큰화': 3, '합니다': 1, '단어로': 1, '해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '사용': 1, '있습니다': 1, '수': 1, '할': 1, '한': 1, '결과는': 1})


In [18]:
print("<각 단어에 매겨진 인덱스 값>\n",token.word_index)

<각 단어에 매겨진 인덱스 값>
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [21]:
text= "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"



token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [22]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [25]:
word_size = len(token.word_index)+1
x = tf.keras.utils.to_categorical(x, num_classes=word_size)

In [26]:
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


문장을 단어 단위로 토큰화하고 그것을 인데스로 만들고 원핫인코딩을 해준다

In [27]:
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

In [28]:
#타깃만들기
classes = np.array([1,1,1,1,1,0,0,0,0,0])

In [29]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [30]:
x = token.texts_to_sequences(docs)
print("리뷰 텍스트 토큰화 결과\n", x)

리뷰 텍스트 토큰화 결과
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [31]:
padded_x = pad_sequences(x, 4)# 4로 맞춰짐
print("패딩 결과\n", padded_x)

패딩 결과
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [32]:
word_size = len(token.word_index) + 1 #꼭 +1해주기

In [34]:
model = Sequential()
model.add(Embedding(word_size,8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              168       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 0s 494ms/step - loss: 0.6970 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6922 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6898 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6875 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6851 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6828 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 997us/step - loss: 0.6805 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6782 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6758 - accuracy: 0.7000
Epoch 11/20
1/1 [==================

In [37]:
print("Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 91ms/step - loss: 0.6503 - accuracy: 0.9000
Accuracy: 0.9000


In [ ]:
#시계열 데이터
